### [ LIFT UI BY BISWAJIT ] ##

# Jai Shree Ram

# Please Add FormAPI And BetterWarp Plugin

# You Can Set Warps Here:

# Subscribe My Channel 'Biswajit 🔥'

Coal_Mine: coalm

Iron_Mine: iromm

Gold_Mine: goldm

Lapis_Mine: lapism

Redstone_Mine: redstonem

Emerald_Mine: emeraldm

Diamond_Mine: diamondm

sanctuary_Mine: sanctuary

# Add Warps 

# Enjoy Plugin
